language: python
os:
  - linux
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev
env: GHK=26eb89ce891a41c26a038b4658129bff29b3fac2
# command to install dependencies
install: "pip install geopy pygithub retrying"
# command to run tests
script: nosetests
